var files_dup =
[
    [ "binaryIO.cpp", "binary_i_o_8cpp.html", "binary_i_o_8cpp" ],
    [ "binaryIO.h", "binary_i_o_8h.html", "binary_i_o_8h" ],
    [ "crsmatrix.cpp", "crsmatrix_8cpp.html", null ],
    [ "crsmatrix.h", "crsmatrix_8h.html", "crsmatrix_8h" ],
    [ "crsmatrix_gpu.h", "crsmatrix__gpu_8h.html", "crsmatrix__gpu_8h" ],
    [ "cuthill_mckee_ordering.cpp", "cuthill__mckee__ordering_8cpp.html", "cuthill__mckee__ordering_8cpp" ],
    [ "cuthill_mckee_ordering.h", "cuthill__mckee__ordering_8h.html", "cuthill__mckee__ordering_8h" ],
    [ "generateCRS.cpp", "generate_c_r_s_8cpp.html", "generate_c_r_s_8cpp" ],
    [ "geom.cpp", "geom_8cpp.html", "geom_8cpp" ],
    [ "geom.h", "geom_8h.html", "geom_8h" ],
    [ "getmatrix.cpp", "getmatrix_8cpp.html", "getmatrix_8cpp" ],
    [ "getmatrix.h", "getmatrix_8h.html", "getmatrix_8h" ],
    [ "info.h", "info_8h.html", "info_8h" ],
    [ "jacsolve.cpp", "jacsolve_8cpp.html", "jacsolve_8cpp" ],
    [ "jacsolve.h", "jacsolve_8h.html", "jacsolve_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "timing.h", "timing_8h.html", "timing_8h" ],
    [ "userset.cpp", "userset_8cpp.html", "userset_8cpp" ],
    [ "userset.h", "userset_8h.html", "userset_8h" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ],
    [ "vdop.cpp", "vdop_8cpp.html", "vdop_8cpp" ],
    [ "vdop.h", "vdop_8h.html", "vdop_8h" ],
    [ "vdop_gpu.h", "vdop__gpu_8h.html", "vdop__gpu_8h" ],
    [ "visualize_results.m", "visualize__results_8m.html", "visualize__results_8m" ]
];